name: NestJS Deployment Pipeline.
on: 
  push:
    branches:
    - main 
    - master
jobs:
  build:
    runs-on: self-hosted
    strategy:
     matrix: 
      node-version: [12.22.9]
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses : actions/setup-node@v3
        with : 
          node-version: ${{matrix.node-version}}   
      - name : Isntall dependencies
        run : npm install
      - name: Build Project
        run: npm run build